package bench

type Spec struct {
	Name             string
	Class            string
	Description      string
	ProfileName      string
	Command          []string
	Display          []string
	Cwd              string
	ExitCode         int
	StdoutFile       string
	StderrFile       string
	ExpectedContains []string
	MinTokenSavings  float64
	MinQualityScore  int
}

func Specs() []Spec {
	return append([]Spec(nil), builtinSpecs...)
}

var builtinSpecs = []Spec{
	{
		Name:        "ls-listing",
		Class:       "directory-listing",
		Description: "Wide plain ls output that should collapse to a short directory preview.",
		ProfileName: "directory-listing",
		Command:     []string{"ls"},
		Display:     []string{"ls"},
		StdoutFile:  "testdata/ls_listing.txt",
		ExpectedContains: []string{
			"docs/",
			"dirs:",
			"files:",
		},
		MinTokenSavings: 20,
		MinQualityScore: 70,
	},
	{
		Name:        "tree-listing",
		Class:       "tree-listing",
		Description: "Nested tree output with footer counts that should truncate cleanly.",
		ProfileName: "directory-listing",
		Command:     []string{"tree"},
		Display:     []string{"tree"},
		StdoutFile:  "testdata/tree_listing.txt",
		ExpectedContains: []string{
			"project",
			"CHANGELOG.md",
			"cmd",
		},
		MinTokenSavings: 15,
		MinQualityScore: 70,
	},
	{
		Name:        "read-markdown",
		Class:       "cat-read",
		Description: "Long markdown file that should reduce to headings and list anchors.",
		ProfileName: "cat-read",
		Command:     []string{"cat", "README.md"},
		Display:     []string{"cat", "README.md"},
		StdoutFile:  "testdata/read_markdown.txt",
		ExpectedContains: []string{
			"# Project Atlas",
			"## Install",
			"- `atlas sync`",
		},
		MinTokenSavings: 40,
		MinQualityScore: 80,
	},
	{
		Name:        "vitest-direct-fail",
		Class:       "vitest-json",
		Description: "Direct Vitest JSON output with one failed suite and multiple passing tests.",
		ProfileName: "vitest-json",
		Command:     []string{"vitest", "run"},
		Display:     []string{"vitest", "run"},
		ExitCode:    1,
		StdoutFile:  "testdata/vitest_direct_fail.json",
		ExpectedContains: []string{
			"suites: pass=3 fail=1",
			"src/button.test.ts",
			"button renders disabled state",
			"Expected: true",
		},
		MinTokenSavings: 60,
		MinQualityScore: 85,
	},
	{
		Name:        "jest-direct-fail",
		Class:       "jest-json",
		Description: "Direct Jest JSON output with one failed assertion and pass noise.",
		ProfileName: "jest-json",
		Command:     []string{"jest", "--runInBand"},
		Display:     []string{"jest", "--runInBand"},
		ExitCode:    1,
		StdoutFile:  "testdata/jest_direct_fail.json",
		ExpectedContains: []string{
			"suites: pass=2 fail=1",
			"src/math.test.ts",
			"math subtracts",
			"Received: 3",
		},
		MinTokenSavings: 60,
		MinQualityScore: 85,
	},
	{
		Name:        "cargo-test-direct-fail",
		Class:       "cargo-test",
		Description: "Direct cargo test failure output with passing chatter, panic context, and rerun hint.",
		ProfileName: "cargo-test",
		Command:     []string{"cargo", "test"},
		Display:     []string{"cargo", "test"},
		ExitCode:    101,
		StdoutFile:  "testdata/cargo_test_direct_fail.txt",
		ExpectedContains: []string{
			"test tests::math::subtracts ... FAILED",
			"thread 'tests::math::subtracts' panicked at src/lib.rs:42:5:",
			"assertion `left == right` failed",
			"error: test failed, to rerun pass `--lib`",
		},
		MinTokenSavings: 50,
		MinQualityScore: 85,
	},
	{
		Name:        "ripgrep-noisy-matches",
		Class:       "ripgrep",
		Description: "Ripgrep results across source files with vendor-like noise that should collapse into grouped file summaries.",
		ProfileName: "ripgrep",
		Command:     []string{"rg", "TODO", "."},
		Display:     []string{"rg", "TODO", "."},
		StdoutFile:  "testdata/ripgrep_noisy_matches.txt",
		ExpectedContains: []string{
			"src/app/main.go (2 matches)",
			"src/search/index.go (2 matches)",
			"src/history/store.go (1 matches)",
			"suppressed noisy paths:",
		},
		MinTokenSavings: 20,
		MinQualityScore: 75,
	},
	{
		Name:        "find-noisy-paths",
		Class:       "path-find",
		Description: "Large find output with source hits mixed with dependency and cache paths that should be suppressed.",
		ProfileName: "path-find",
		Command:     []string{"find", ".", "-name", "*.go"},
		Display:     []string{"find", ".", "-name", "*.go"},
		StdoutFile:  "testdata/find_noisy_paths.txt",
		ExpectedContains: []string{
			"6 matches",
			"cmd/szr/main.go",
			"internal/engine/run.go",
			"suppressed noisy paths:",
		},
		MinTokenSavings: 20,
		MinQualityScore: 75,
	},
	{
		Name:        "clean-pass",
		Class:       "clean-pass",
		Description: "Structured go test success output with multiple passing packages.",
		ProfileName: "go-test-json",
		Command:     []string{"go", "test", "./..."},
		Display:     []string{"go", "test", "./..."},
		StdoutFile:  "testdata/go_test_clean.jsonl",
		ExpectedContains: []string{
			"packages: pass=3 fail=0",
			"all tests passed",
		},
		MinTokenSavings: 60,
		MinQualityScore: 95,
	},
	{
		Name:        "noisy-fail",
		Class:       "noisy-fail",
		Description: "Unstructured test failure output with passing noise, stack traces, and tool errors.",
		ProfileName: "generic-test",
		Command:     []string{"test", "npm", "run", "test", "--", "--runInBand"},
		Display:     []string{"test", "npm", "run", "test"},
		ExitCode:    1,
		StdoutFile:  "testdata/noisy_fail.txt",
		ExpectedContains: []string{
			"button.test.tsx > Button > renders primary state",
			"Error: expected primary button to be visible",
			"error Command failed with exit code 1.",
		},
		MinTokenSavings: 20,
		MinQualityScore: 80,
	},
	{
		Name:        "diff-stat",
		Class:       "diff-stat-output",
		Description: "Mixed patch and stat-heavy git diff output across multiple files.",
		ProfileName: "git-diff",
		Command:     []string{"git", "diff"},
		Display:     []string{"git", "diff"},
		StdoutFile:  "testdata/git_diff.txt",
		ExpectedContains: []string{
			"files=2",
			"cmd/szr/main.go",
			"2 files changed, 13 insertions(+), 4 deletions(-)",
		},
		MinTokenSavings: 15,
		MinQualityScore: 70,
	},
	{
		Name:        "giant-diff",
		Class:       "giant-diff",
		Description: "Large git diff with many files and stat lines that should collapse to a stable preview.",
		ProfileName: "git-diff",
		Command:     []string{"git", "diff", "--stat"},
		Display:     []string{"git", "diff"},
		StdoutFile:  "testdata/giant_diff.txt",
		ExpectedContains: []string{
			"files=12",
			"internal/parser/lexer.go",
			"internal/parser/token_test.go",
		},
		MinTokenSavings: 50,
		MinQualityScore: 75,
	},
	{
		Name:        "repeated-logs",
		Class:       "repeated-logs",
		Description: "Long repeated application logs that should collapse to a shallow preview.",
		ProfileName: "generic-summary",
		Command:     []string{"summary", "tail", "-n", "200", "var/log/build.log"},
		Display:     []string{"summary", "tail", "-n", "200", "var/log/build.log"},
		StdoutFile:  "testdata/repeated_logs.txt",
		ExpectedContains: []string{
			"2026-05-20T21:00:00Z INFO worker.1 step=compile status=running",
			"... +8 more lines",
		},
		MinTokenSavings: 30,
		MinQualityScore: 70,
	},
	{
		Name:        "git-status-noisy",
		Class:       "git-status",
		Description: "Busy git status output with many unstaged and untracked paths.",
		ProfileName: "git-status",
		Command:     []string{"git", "status"},
		Display:     []string{"git", "status"},
		StdoutFile:  "testdata/git_status.txt",
		ExpectedContains: []string{
			"main...origin/main",
			"staged=",
			"unstaged:",
			"untracked:",
		},
		MinTokenSavings: 30,
		MinQualityScore: 80,
	},
	{
		Name:        "git-log-history",
		Class:       "git-log",
		Description: "Long oneline git history that should collapse to a short commit preview.",
		ProfileName: "git-log",
		Command:     []string{"git", "log"},
		Display:     []string{"git", "log"},
		StdoutFile:  "testdata/git_log.txt",
		ExpectedContains: []string{
			"f71d6ac Add stable Homebrew formula",
			"... +",
		},
		MinTokenSavings: 20,
		MinQualityScore: 70,
	},
	{
		Name:        "compiler-diagnostics",
		Class:       "compiler-diagnostics",
		Description: "Go compiler output with download chatter on stdout and errors on stderr.",
		ProfileName: "go-build",
		Command:     []string{"go", "build", "./..."},
		Display:     []string{"go", "build", "./..."},
		ExitCode:    1,
		StdoutFile:  "testdata/compiler_diagnostics.stdout.txt",
		StderrFile:  "testdata/compiler_diagnostics.stderr.txt",
		ExpectedContains: []string{
			"internal/engine/runner.go:18:2: error: undefined: missingSymbol",
			"warning: deprecated helper benchmarkHarness will be removed",
		},
		MinTokenSavings: 10,
		MinQualityScore: 80,
	},
	{
		Name:        "mixed-stdio-fail",
		Class:       "mixed-stdout-stderr-fail",
		Description: "Failure that spreads actionable identifiers across stdout and stderr with summary noise.",
		ProfileName: "generic-test",
		Command:     []string{"test", "pnpm", "exec", "playwright", "test"},
		Display:     []string{"test", "pnpm", "exec", "playwright", "test"},
		ExitCode:    1,
		StdoutFile:  "testdata/mixed_stdio_fail.stdout.txt",
		StderrFile:  "testdata/mixed_stdio_fail.stderr.txt",
		ExpectedContains: []string{
			"FAIL tests/e2e/checkout.spec.ts > checkout flow > submits order",
			"TimeoutError: locator.click: Timeout 5000ms exceeded.",
			"Error: worker exited with code 1",
		},
		MinTokenSavings: 20,
		MinQualityScore: 85,
	},
}
