package bench

type Spec struct {
	Name             string
	Class            string
	Description      string
	ProfileName      string
	Command          []string
	Display          []string
	Cwd              string
	ExitCode         int
	StdoutFile       string
	StderrFile       string
	ExpectedContains []string
	MinTokenSavings  float64
	MinQualityScore  int
}

func Specs() []Spec {
	return append([]Spec(nil), builtinSpecs...)
}

var builtinSpecs = []Spec{
	{
		Name:        "ls-listing",
		Class:       "directory-listing",
		Description: "Wide plain ls output that should collapse to a short directory preview.",
		ProfileName: "directory-listing",
		Command:     []string{"ls"},
		Display:     []string{"ls"},
		StdoutFile:  "testdata/ls_listing.txt",
		ExpectedContains: []string{
			"docs/",
			"dirs:",
			"files:",
		},
		MinTokenSavings: 20,
		MinQualityScore: 70,
	},
	{
		Name:        "tree-listing",
		Class:       "tree-listing",
		Description: "Nested tree output with footer counts that should truncate cleanly.",
		ProfileName: "directory-listing",
		Command:     []string{"tree"},
		Display:     []string{"tree"},
		StdoutFile:  "testdata/tree_listing.txt",
		ExpectedContains: []string{
			"project",
			"CHANGELOG.md",
			"cmd",
		},
		MinTokenSavings: 15,
		MinQualityScore: 70,
	},
	{
		Name:        "read-markdown",
		Class:       "cat-read",
		Description: "Long markdown file that should reduce to headings and list anchors.",
		ProfileName: "cat-read",
		Command:     []string{"cat", "README.md"},
		Display:     []string{"cat", "README.md"},
		StdoutFile:  "testdata/read_markdown.txt",
		ExpectedContains: []string{
			"# Project Atlas",
			"## Install",
			"- `atlas sync`",
		},
		MinTokenSavings: 40,
		MinQualityScore: 80,
	},
	{
		Name:        "vitest-direct-fail",
		Class:       "vitest-json",
		Description: "Direct Vitest JSON output with one failed suite and multiple passing tests.",
		ProfileName: "vitest-json",
		Command:     []string{"vitest", "run"},
		Display:     []string{"vitest", "run"},
		ExitCode:    1,
		StdoutFile:  "testdata/vitest_direct_fail.json",
		ExpectedContains: []string{
			"suites: pass=3 fail=1",
			"src/button.test.ts",
			"button renders disabled state",
			"Expected: true",
		},
		MinTokenSavings: 60,
		MinQualityScore: 85,
	},
	{
		Name:        "jest-direct-fail",
		Class:       "jest-json",
		Description: "Direct Jest JSON output with one failed assertion and pass noise.",
		ProfileName: "jest-json",
		Command:     []string{"jest", "--runInBand"},
		Display:     []string{"jest", "--runInBand"},
		ExitCode:    1,
		StdoutFile:  "testdata/jest_direct_fail.json",
		ExpectedContains: []string{
			"suites: pass=2 fail=1",
			"src/math.test.ts",
			"math subtracts",
			"Received: 3",
		},
		MinTokenSavings: 60,
		MinQualityScore: 85,
	},
	{
		Name:        "cargo-test-direct-fail",
		Class:       "cargo-test",
		Description: "Direct cargo test failure output with passing chatter, panic context, and rerun hint.",
		ProfileName: "cargo-test",
		Command:     []string{"cargo", "test"},
		Display:     []string{"cargo", "test"},
		ExitCode:    101,
		StdoutFile:  "testdata/cargo_test_direct_fail.txt",
		ExpectedContains: []string{
			"test tests::math::subtracts ... FAILED",
			"thread 'tests::math::subtracts' panicked at src/lib.rs:42:5:",
			"assertion `left == right` failed",
			"error: test failed, to rerun pass `--lib`",
		},
		MinTokenSavings: 50,
		MinQualityScore: 85,
	},
	{
		Name:        "ripgrep-noisy-matches",
		Class:       "ripgrep",
		Description: "Ripgrep results across source files with vendor-like noise that should collapse into grouped file summaries.",
		ProfileName: "ripgrep",
		Command:     []string{"rg", "TODO", "."},
		Display:     []string{"rg", "TODO", "."},
		StdoutFile:  "testdata/ripgrep_noisy_matches.txt",
		ExpectedContains: []string{
			"src/app/main.go:12: TODO tighten benchmark preview reporting so raw versus reduced output is visible in one place (2 matches)",
			"src/search/index.go:8: TODO skip generated fixture directories during benchmark runs by default (2 matches)",
			"src/history/store.go:77: TODO persist comparison snapshots for benchmark fixtures when quality drops (1 matches)",
			"suppressed noisy paths:",
		},
		MinTokenSavings: 20,
		MinQualityScore: 75,
	},
	{
		Name:        "find-noisy-paths",
		Class:       "path-find",
		Description: "Large find output with source hits mixed with dependency and cache paths that should be suppressed.",
		ProfileName: "path-find",
		Command:     []string{"find", ".", "-name", "*.go"},
		Display:     []string{"find", ".", "-name", "*.go"},
		StdoutFile:  "testdata/find_noisy_paths.txt",
		ExpectedContains: []string{
			"6 matches",
			"cmd/szr/main.go",
			"test/filters/search_test.go",
			"suppressed noisy paths:",
		},
		MinTokenSavings: 20,
		MinQualityScore: 75,
	},
	{
		Name:        "clean-pass",
		Class:       "clean-pass",
		Description: "Structured go test success output with multiple passing packages.",
		ProfileName: "go-test-json",
		Command:     []string{"go", "test", "./..."},
		Display:     []string{"go", "test", "./..."},
		StdoutFile:  "testdata/go_test_clean.jsonl",
		ExpectedContains: []string{
			"3 packages passed",
		},
		MinTokenSavings: 60,
		MinQualityScore: 95,
	},
	{
		Name:        "noisy-fail",
		Class:       "noisy-fail",
		Description: "Unstructured test failure output with passing noise, stack traces, and tool errors.",
		ProfileName: "generic-test",
		Command:     []string{"test", "npm", "run", "test", "--", "--runInBand"},
		Display:     []string{"test", "npm", "run", "test"},
		ExitCode:    1,
		StdoutFile:  "testdata/noisy_fail.txt",
		ExpectedContains: []string{
			"button.test.tsx > Button > renders primary state",
			"Error: expected primary button to be visible",
			"error Command failed with exit code 1.",
		},
		MinTokenSavings: 20,
		MinQualityScore: 80,
	},
	{
		Name:        "diff-stat",
		Class:       "diff-stat-output",
		Description: "Mixed patch and stat-heavy git diff output across multiple files.",
		ProfileName: "git-diff",
		Command:     []string{"git", "diff"},
		Display:     []string{"git", "diff"},
		StdoutFile:  "testdata/git_diff.txt",
		ExpectedContains: []string{
			"files=2",
			"cmd/szr/main.go",
			"2 files changed, 13 insertions(+), 4 deletions(-)",
		},
		MinTokenSavings: 15,
		MinQualityScore: 70,
	},
	{
		Name:        "giant-diff",
		Class:       "giant-diff",
		Description: "Large git diff with many files and stat lines that should collapse to a stable preview.",
		ProfileName: "git-diff",
		Command:     []string{"git", "diff", "--stat"},
		Display:     []string{"git", "diff"},
		StdoutFile:  "testdata/giant_diff.txt",
		ExpectedContains: []string{
			"files=12",
			"internal/parser/lexer.go",
			"internal/parser/token_test.go",
		},
		MinTokenSavings: 50,
		MinQualityScore: 75,
	},
	{
		Name:        "repeated-logs",
		Class:       "repeated-logs",
		Description: "Long repeated application logs that should collapse to a shallow preview.",
		ProfileName: "generic-summary",
		Command:     []string{"summary", "tail", "-n", "200", "var/log/build.log"},
		Display:     []string{"summary", "tail", "-n", "200", "var/log/build.log"},
		StdoutFile:  "testdata/repeated_logs.txt",
		ExpectedContains: []string{
			"2026-05-20T21:00:00Z INFO worker.1 step=compile status=running (x20)",
		},
		MinTokenSavings: 30,
		MinQualityScore: 70,
	},
	{
		Name:        "git-status-noisy",
		Class:       "git-status",
		Description: "Busy git status output with many unstaged and untracked paths.",
		ProfileName: "git-status",
		Command:     []string{"git", "status"},
		Display:     []string{"git", "status"},
		StdoutFile:  "testdata/git_status.txt",
		ExpectedContains: []string{
			"main...origin/main",
			"staged=",
			"unstaged:",
			"untracked:",
		},
		MinTokenSavings: 30,
		MinQualityScore: 80,
	},
	{
		Name:        "git-log-history",
		Class:       "git-log",
		Description: "Long oneline git history that should collapse to a short commit preview.",
		ProfileName: "git-log",
		Command:     []string{"git", "log"},
		Display:     []string{"git", "log"},
		StdoutFile:  "testdata/git_log.txt",
		ExpectedContains: []string{
			"f71d6ac Add stable Homebrew formula",
			"... +",
		},
		MinTokenSavings: 20,
		MinQualityScore: 70,
	},
	{
		Name:        "compiler-diagnostics",
		Class:       "compiler-diagnostics",
		Description: "Go compiler output with download chatter on stdout and errors on stderr.",
		ProfileName: "go-build",
		Command:     []string{"go", "build", "./..."},
		Display:     []string{"go", "build", "./..."},
		ExitCode:    1,
		StdoutFile:  "testdata/compiler_diagnostics.stdout.txt",
		StderrFile:  "testdata/compiler_diagnostics.stderr.txt",
		ExpectedContains: []string{
			"internal/engine/runner.go:18:2: error: undefined: missingSymbol",
			"warning: deprecated helper benchmarkHarness will be removed",
		},
		MinTokenSavings: 10,
		MinQualityScore: 80,
	},
	{
		Name:        "mixed-stdio-fail",
		Class:       "mixed-stdout-stderr-fail",
		Description: "Failure that spreads actionable identifiers across stdout and stderr with summary noise.",
		ProfileName: "generic-test",
		Command:     []string{"test", "pnpm", "exec", "playwright", "test"},
		Display:     []string{"test", "pnpm", "exec", "playwright", "test"},
		ExitCode:    1,
		StdoutFile:  "testdata/mixed_stdio_fail.stdout.txt",
		StderrFile:  "testdata/mixed_stdio_fail.stderr.txt",
		ExpectedContains: []string{
			"FAIL tests/e2e/checkout.spec.ts > checkout flow > submits order",
			"TimeoutError: locator.click: Timeout 5000ms exceeded.",
			"Error: worker exited with code 1",
		},
		MinTokenSavings: 20,
		MinQualityScore: 85,
	},
	{
		Name:        "git-fetch-noisy",
		Class:       "git-transfer",
		Description: "Full git fetch transcript with remote/receiving/resolving progress and several ref updates.",
		ProfileName: "git-fetch",
		Command:     []string{"git", "fetch", "origin", "--prune"},
		Display:     []string{"git", "fetch", "origin"},
		StderrFile:  "testdata/git_fetch_noisy.txt",
		ExpectedContains: []string{
			"From github.com:devr-tools/szr",
			"objects: 5210 (4.82 MiB), deltas: 3054",
			"dae313d..8f21c04 main -> origin/main",
			"... +2 more refs",
		},
		MinTokenSavings: 80,
		MinQualityScore: 80,
	},
	{
		Name:        "go-mod-download",
		Class:       "go-mod",
		Description: "go mod tidy output with 30+ module downloads plus added/upgraded/removed changes.",
		ProfileName: "go-mod",
		Command:     []string{"go", "mod", "tidy"},
		Display:     []string{"go", "mod", "tidy"},
		StderrFile:  "testdata/go_mod_download.txt",
		ExpectedContains: []string{
			"downloaded 34 modules (top: github.com/spf13/cobra, github.com/spf13/pflag, golang.org/x/sys, ...)",
			"go: upgraded golang.org/x/sys v0.20.0 => v0.21.0",
			"... +2 more dependency changes",
		},
		MinTokenSavings: 65,
		MinQualityScore: 80,
	},
	{
		Name:        "kubectl-apply-many",
		Class:       "kubectl-apply",
		Description: "kubectl apply across ~40 resources with configured/unchanged/created results and a warning.",
		ProfileName: "kubectl-apply",
		Command:     []string{"kubectl", "apply", "-f", "deploy/manifests/"},
		Display:     []string{"kubectl", "apply", "-f", "deploy/manifests/"},
		StdoutFile:  "testdata/kubectl_apply_many.stdout.txt",
		StderrFile:  "testdata/kubectl_apply_many.stderr.txt",
		ExpectedContains: []string{
			"resources: configured=18 unchanged=14 created=8",
			"Warning: resource configmaps/feature-flags is missing",
			"configured: deployment.apps/web, deployment.apps/api, deployment.apps/worker +15 more",
			"created: deployment.apps/link-preview",
		},
		MinTokenSavings: 60,
		MinQualityScore: 80,
	},
	{
		Name:        "docker-pull-layers",
		Class:       "docker-transfer",
		Description: "Multi-layer docker pull with per-layer progress bars, digests, and final status.",
		ProfileName: "docker-transfer",
		Command:     []string{"docker", "pull", "registry.example.com/platform/api:1.42.0"},
		Display:     []string{"docker", "pull", "registry.example.com/platform/api:1.42.0"},
		StdoutFile:  "testdata/docker_pull_layers.txt",
		ExpectedContains: []string{
			"pulled 8 layers (3 already existed)",
			"Digest: sha256:",
			"Status: Downloaded newer image for registry.example.com/platform/api:1.42.0",
		},
		MinTokenSavings: 85,
		MinQualityScore: 80,
	},
	{
		Name:        "terraform-plan",
		Class:       "terraform-plan",
		Description: "Realistic terraform plan with several resource blocks, attribute diffs, a warning, and the Plan summary.",
		ProfileName: "build-system",
		Command:     []string{"terraform", "plan", "-no-color"},
		Display:     []string{"terraform", "plan"},
		StdoutFile:  "testdata/terraform_plan.txt",
		ExpectedContains: []string{
			"Plan: 5 to add, 2 to change, 1 to destroy.",
			"# aws_instance.web[0] will be created",
			"Warning: Argument is deprecated",
		},
		MinTokenSavings: 75,
		MinQualityScore: 75,
	},
	{
		Name:        "gh-pr-checks-watch",
		Class:       "gh-pr-checks",
		Description: "gh pr checks --watch transcript with repeated table repaints converging to one failing check.",
		ProfileName: "gh-pr-checks",
		Command:     []string{"gh", "pr", "checks", "42", "--watch"},
		Display:     []string{"gh", "pr", "checks", "42", "--watch"},
		ExitCode:    8,
		StdoutFile:  "testdata/gh_pr_checks_watch.txt",
		ExpectedContains: []string{
			"checks: 13 pass, 1 fail, 1 skipping (15 total)",
			"watched 3 updates",
			"fail: test (windows-latest quick)",
		},
		MinTokenSavings: 85,
		MinQualityScore: 80,
	},
	{
		Name:        "repeated-timestamped-logs",
		Class:       "repeated-logs",
		Description: "200+ timestamped INFO/WARN log lines with a handful of distinct messages that should fold hard.",
		ProfileName: "generic-summary",
		Command:     []string{"summary", "tail", "-n", "220", "var/log/app.log"},
		Display:     []string{"summary", "tail", "-n", "220", "var/log/app.log"},
		StdoutFile:  "testdata/repeated_timestamped_logs.txt",
		ExpectedContains: []string{
			"INFO worker.3 job=link-sync status=running (x62)",
			"INFO api.request handled path=/v1/links status=200 (x84)",
			"WARN db.pool slow query detected query=links_by_profile",
			"INFO worker.3 job=link-sync status=complete records=48210",
		},
		MinTokenSavings: 85,
		MinQualityScore: 80,
	},
	{
		Name:        "service-log-severity",
		Class:       "log-read",
		Description: "Timestamped service log with buried ERROR lines that should render as a severity histogram plus deduplicated messages.",
		ProfileName: "cat-read",
		Command:     []string{"cat", "logs/service.log"},
		Display:     []string{"cat", "logs/service.log"},
		StdoutFile:  "testdata/service_log.log",
		ExpectedContains: []string{
			"223 lines:",
			"6 ERROR",
			"ERROR connection reset by peer while flushing batch (x3, 10:00:15–10:00:45)",
			"ERROR retrying flush attempt 1/3 (x3, 10:00:15–10:00:45)",
			"WARN slow query detected on orders index (x",
		},
		MinTokenSavings: 85,
		MinQualityScore: 90,
	},
	{
		Name:        "pnpm-test-text-fail",
		Class:       "js-package-test",
		Description: "Plain-text Vitest run behind `pnpm test` with two failing specs whose names and assertions must survive.",
		ProfileName: "js-package-test",
		Command:     []string{"pnpm", "test"},
		Display:     []string{"pnpm", "test"},
		ExitCode:    1,
		StdoutFile:  "testdata/pnpm_test_text_fail.txt",
		ExpectedContains: []string{
			"renders empty cart total",
			"applies discount code",
			"AssertionError: expected '$0.01' to be '$0.00'",
			"Tests  2 failed | 41 passed (43)",
		},
		MinTokenSavings: 47,
		MinQualityScore: 90,
	},
	{
		Name:        "pnpm-add-registry-404",
		Class:       "js-workspace",
		Description: "pnpm add hitting a registry 404 where the package spec and error code line must survive.",
		ProfileName: "js-workspace",
		Command:     []string{"pnpm", "add", "@acme/design-tokens"},
		Display:     []string{"pnpm", "add", "@acme/design-tokens"},
		ExitCode:    1,
		StderrFile:  "testdata/pnpm_add_registry_404.txt",
		ExpectedContains: []string{
			"ERR_PNPM_FETCH_404",
			"@acme/design-tokens",
			"is not in the npm registry",
		},
		MinTokenSavings: 24,
		MinQualityScore: 90,
	},
	{
		Name:        "cargo-build-direct-err",
		Class:       "cargo-build",
		Description: "cargo build failure with two coded rustc errors buried under compile progress chatter.",
		ProfileName: "cargo-build",
		Command:     []string{"cargo", "build"},
		Display:     []string{"cargo", "build"},
		ExitCode:    101,
		StderrFile:  "testdata/cargo_build_direct_err.txt",
		ExpectedContains: []string{
			"error[E0599]: no method named `finalise` found for struct `InvoiceBuilder`",
			"error[E0382]: borrow of moved value: `line_items`",
			"--> src/invoice.rs:214:30",
			"error: could not compile `billing-core` (lib) due to 2 previous errors",
		},
		MinTokenSavings: 50,
		MinQualityScore: 90,
	},
	{
		Name:        "dotnet-build-fail",
		Class:       "dotnet-build",
		Description: "MSBuild failure output with duplicated coded diagnostics and restore noise.",
		ProfileName: "dotnet-build",
		Command:     []string{"dotnet", "build"},
		Display:     []string{"dotnet", "build"},
		ExitCode:    1,
		StdoutFile:  "testdata/dotnet_build_fail.txt",
		ExpectedContains: []string{
			"error CS0103",
			"error CS1002: ; expected",
			"InvoiceService.cs(93,52)",
			"Build FAILED.",
		},
		MinTokenSavings: 49,
		MinQualityScore: 90,
	},
}
